personal_blog/blueprints/blog.py
from flask import Blueprint, render_template, request, flash, current_app
from personal_blog.models import Post, Category,Admin,Log

from personal_blog.form import LoginForm, RegisterForm, PostForm, AdminForm, SetPasswordform, CategoryForm,SearchForm
# import personal_blog.config as config
import os
blog_bp = Blueprint('blog', __name__)


# .filter(Post.category.name != 'this_site', Post.category.name != 'individual_resume')
@blog_bp.route('/')
def index():
    page = request.args.get('page', 1, type=int)  # 从查询字符串中获取当前页数
    cate1 = Category.query.filter_by(name='网站介绍').first()    # 网站介绍的分类。
    cate2 = Category.query.filter_by(name='个人介绍').first()  # 关于的分类。
    cate3 = Category.query.filter_by(name='生活').first()           # 文字的分类，起的名称是life。
    per_page = 8    # 每页的数量
    pagination = Post.query.filter(Post.category != cate1, Post.category != cate2, Post.category != cate3).order_by(Post.timestamp.desc()).paginate(page, per_page=per_page) # 分页对象
    posts = pagination.items    # 当前页数记录的列表
    return render_template('blog/index.html', pagination=pagination, posts=posts)


@blog_bp.route('/life')
def index_life():
    page = request.args.get('page', 1, type=int)  # 从查询字符串中获取当前页数
    cate = Category.query.filter_by(name='生活').first()
    per_page = 8  # 每页的数量
    pagination = Post.query.filter(Post.category == cate).order_by(Post.timestamp.desc()).paginate(page, per_page=per_page)  # 分页对象
    posts = pagination.items  # 当前页数记录的列表
    return render_template('blog/index.html', pagination=pagination, posts=posts)


@blog_bp.route('/post/<int:post_id>', methods=['GET', 'POST'])
def show_post(post_id):
    post = Post.query.filter().get_or_404(post_id)
    page = request.args.get('page', 1, type=int)
    per_page = 8
    pagination = Post.query.order_by(Post.timestamp.desc()).paginate(page, per_page=per_page)

    return render_template('blog/post.html', post=post, pagination=pagination)


@blog_bp.route('/category/<int:category_id>')
def show_category(category_id):
    category = Category.query.get_or_404(category_id)
    page = request.args.get('page', 1, type=int)
    per_page = 5
    pagination = Post.query.with_parent(category).order_by(Post.timestamp.desc()).paginate(page, per_page)
    posts = pagination.items
    return render_template('blog/category.html', category=category, pagination=pagination, posts=posts)


@blog_bp.route('/my_blog')
def show_my_blog():
    with open('personal_blog/config', 'r') as f:
        s = f.read()
    id = int(s)
    print(id)
    admin = Admin.query.get_or_404(id)
    page = request.args.get('page', 1, type=int)
    per_page = 5
    pagination = Post.query.with_parent(admin).order_by(Post.timestamp.desc()).paginate(page, per_page)
    posts = pagination.items
    return render_template('blog/my_blog.html', admin=admin, pagination=pagination, posts=posts)

@blog_bp.route('/log')
def log():
    logs = Log.query.all()
    for i in logs:
        print(i.ip)
    return render_template('blog/log.html', logs= logs)


@blog_bp.route('/search',methods=['GET', 'POST'])
def search():
    # print('ss')
    form = SearchForm()
    if form.validate_on_submit():
        search= form.search.data
        page = request.args.get('page', 1, type=int)
        per_page = 5
        pagination = Post.query.filter(Post.title.like('%'+search+'%')).order_by(Post.timestamp.desc()).paginate(page, per_page)
        posts = pagination.items
        return render_template('blog/show_search.html',  pagination=pagination, posts=posts)
    # category = Category.query.get_or_404(category_id)

    return render_template('blog/search.html', form=form)


@blog_bp.route('/individual_resume')
def individual_resume():
    cate = Category.query.filter_by(name='个人介绍').first()
    post = Post.query.filter_by(category=cate).first()
    return render_template('blog/individual_resume.html', post=post)


@blog_bp.route('/this_site')
def this_site():
    cate = Category.query.filter_by(name='网站介绍').first()
    post = Post.query.filter_by(category=cate).first()
    return render_template('blog/this_site.html', post=post)

personal_blog/templates/blog/_posts.html
{% for post in posts %}
    <div class="post2">

        <div class="row">
            <h2 class="art-title title1" style="text-align: center"><a
                    href="{{ url_for('.show_post', post_id = post.id) }}">{{ post.title }}</a></h2>

        </div>
        <div class="row">
            <div class="col-md-2">
            </div>

            <div class="col-md-8 post1">
                <p>
                    {{ post.body|striptags|truncate }}
                    <small><a href="{{ url_for('.show_post', post_id = post.id) }}">阅读更多</a></small>
                </p>
            </div>

            <div class="col-md-2">
            </div>
        </div>
        <div class="row">
            <br>
        </div>
        <div class="row">
            <div class="col-md-1">

            </div>


            <div class="col-md-10">
                <small>

                    文章分类:
                    <a href="{{ url_for('.show_category', category_id=post.category.id) }}" style="color:#6699FF">{{ post.category.name }}</a>

                    <span style="float:right">发布于：{{ moment(post.timestamp).format('LLL') }}</span>

                </small>
            </div>

            <div class="col-md-1">

            </div>
        </div>
    </div>
    {% if not loop.last %}
        <hr>
    {% endif %}

{% endfor %}

personal_blog/templates/blog/category.html
{% extends 'base.html' %}
{% from 'bootstrap/pagination.html' import render_pagination %}

{% block title %}{{ category.name }}{% endblock %}

{% block content %}
    <div class="page-header">
        <h1>文章类型: {{ category.name }}</h1>
        <p class="text-muted">{{ category.posts|length }} posts</p>
    </div>
    <div class="row">
        <div class="col-sm-8">
            {% include "blog/_posts.html" %}
            <div class="page-footer">{{ render_pagination(pagination) }}</div>
        </div>
        <!--
        <div class="col-sm-4 sidebar">
            {% include "blog/sidebar.html" %}
        </div>
        -->
    </div>
{% endblock %}

personal_blog/templates/blog/index.html
{% extends 'base.html' %}
{% from 'bootstrap/pagination.html' import render_pagination %}
{%block title %}PLX的个人网站{% endblock %}





{% block content %}
    <div>
        <div>
            {% include 'blog/_posts.html' %}

            <div class="row">

                <div class="col-md-8">
                     {% if posts %}
                <div class="pag">{{ render_pagination(pagination) }}</div>
            {% endif %}
                </div>

                <div class="col-md-2"/>
            </div>

        </div>

<!--
        <div class="col-sm-4 sidebar">
{#            {% include 'blog/sidebar.html' %}#}
        </div>
-->
    </div>


{% endblock %}

personal_blog/templates/blog/individual_resume.html
{% extends 'base.html' %}


{% block head %}
    {{ super() }}
    {{ ckeditor.load_code_theme() }}  <!-- 这个地方为了实现代码高亮！ -->
{% endblock %}


{% block content %}

<div class="page-header">
        <h1 align="center"><font color="black">{{ post.title }}</font>
            <span class="float-right">
      </span>
        </h1>
</div>





<div class="row">
        <div class="col-sm-8" >
            {{ post.body|safe }}
            <hr>

            <div class="modal fade postLinkModal" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel"
                 aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel">Permalink</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">

                        </div>
                    </div>
                </div>
            </div>
        </div>
</div>


{% endblock %}

personal_blog/templates/blog/log.html
{% extends 'base.html' %}
{% from 'bootstrap/form.html' import render_form %}

{% block title %}搜索页面{% endblock %}




{% block content %}

<table class="table table-striped table-bordered table-hover">

    <tr>
        <th>IP</th>
        <th>用户</th>
        <th>操作</th>
    </tr>
    {% for log in logs %}
        <tr>
            <td>{{log.ip}}</td>
            <td>{{log.operate_user}}</td>
            <td>{{log.operate}}</td>
        </tr>

        {% if not loop.last %}
            <hr>
        {% endif %}

    {% endfor %}

</table>


{% endblock %}

personal_blog/templates/blog/my_blog.html
{% extends 'base.html' %}
{% from 'bootstrap/pagination.html' import render_pagination %}

{% block title %}{{ admin.name }}{% endblock %}

{% block content %}
    <div class="page-header">
        <h1>博客: {{ admin.username }}</h1>
        <p class="text-muted">{{ admin.posts|length }} posts</p>
    </div>
    <div class="row">
        <div class="col-sm-8">
            {% include "blog/_posts.html" %}
            <div class="page-footer">{{ render_pagination(pagination) }}</div>
        </div>
        <!--
        <div class="col-sm-4 sidebar">
            {% include "blog/sidebar.html" %}
        </div>
        -->
    </div>
{% endblock %}

personal_blog/templates/blog/post.html
{% extends 'post_detail.html' %}



{% block title %} {{ post.title }} {% endblock title %}
{% block daima %} {{ ckeditor.load_code_theme() }}  <!-- 这个地方为了实现代码高亮！ --> {% endblock daima %}




{% block content %}

    <div class="page-header">
        <h1 align="center"><font color="black">{{ post.title }}</font>
            <span class="float-right">
      </span>
        </h1>
        {% if current_user.is_authenticated %}
            <span style="float:right"><a class="btn btn-info btn-sm"
                                         href="{{ url_for('admin.edit_post', post_id=post.id) }}">编辑</a> </span>
        {% endif %}
    </div>





    <div class="row">
        <div class="col-sm-8">
            <div class="post_body">
                {{ post.body|safe }}
            </div>
            <hr>

            <div class="modal fade postLinkModal" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel"
                 aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel">Permalink</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <div class="form-group">
                                <input type="text" class="form-control"
                                       value="{{ url_for('.show_post', post_id=post.id, _external=True) }}" readonly>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


{% endblock %}

personal_blog/templates/blog/search.html
{% extends 'base.html' %}
{% from 'bootstrap/form.html' import render_form %}

{% block title %}搜索页面{% endblock %}




{% block content %}
        <div class="container-fluid">
    <div class="row">
        <div class="col-md-5"></div>
        <div class="title2 col-md-1">
            <h1>搜索</h1>
        </div>

        <div class="col-md-5"></div>
    </div>
    <div class="row">
        <div class="col-md-5"></div>

        <div class="col-md-5">
            <form method="post">
                {{ form.csrf_token }}

                {{ form.search }}

                {{ form.submit }}

            </form>
            </div>
        </div>
    </div>

    <div class="row">
        <br>
    </div>
        </div>
{% endblock %}

{#{% block footer %}{% endblock %}#}

personal_blog/templates/blog/show_search.html
{% extends 'base.html' %}
{% from 'bootstrap/pagination.html' import render_pagination %}

{#{% block title %}{{ admin.name }}{% endblock %}#}

{% block content %}
    <div class="page-header">
        <h1>搜索结果: </h1>
{#        <p class="text-muted">{{ admin.posts|length }} posts</p>#}
    </div>
    <div class="row">
        <div class="col-sm-8">
            {% include "blog/_posts.html" %}
            <div class="page-footer">{{ render_pagination(pagination) }}</div>
        </div>
        <!--
        <div class="col-sm-4 sidebar">
            {% include "blog/sidebar.html" %}
        </div>
        -->
    </div>
{% endblock %}

personal_blog/templates/blog/sidebar.html
<div class="card mb-3">
        <div class="card-header">去往～</div>
        <ul class="list-group list-group-flush">
                <li class="list-group-item  list-group-item-action d-flex justify-content-between align-items-center">
                    <a href="{{ url_for('blog.individual_resume') }}" target="_blank">关于</a>

                </li>
            <li class="list-group-item  list-group-item-action d-flex justify-content-between align-items-center">
                    <a href="{{ url_for('blog.this_site') }}" target="_blank">这个网站介绍</a>
                </li>
{#            <li class="list-group-item  list-group-item-action d-flex justify-content-between align-items-center">#}
{#                    <a href="{{ url_for('static', filename='wx.JPG') }}" target="_blank">微信</a>#}
{#                </li>#}
{#            <li class="list-group-item  list-group-item-action d-flex justify-content-between align-items-center">#}
{#                    <a href="https://www.cnblogs.com/dairuiquan/" target="_blank">博客园</a>#}
{#                </li>#}
{#            <li class="list-group-item  list-group-item-action d-flex justify-content-between align-items-center">#}
{#                    <a href="https://github.com/zzsealy" target="_blank">github</a>#}
{#                </li>#}

        </ul>
    </div>

personal_blog/templates/blog/this_site.html
{% extends 'base.html' %}


    {% block title %} {{ post.title }} {% endblock title %}
    {% block daima %} {{ ckeditor.load_code_theme() }}  <!-- 这个地方为了实现代码高亮！ --> {% endblock daima %}


{% block content %}

<div class="page-header">
        <h1 align="center"><font>{{ post.title }}</font>
            <span class="float-right">
      </span>
        </h1>
</div>





<div class="row">
        <div class="col-sm-8" >
            {{ post.body|safe }}
            <hr>

            <div class="modal fade postLinkModal" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel"
                 aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel">Permalink</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times</span>
                            </button>
                        </div>
                        <div class="modal-body">

                        </div>
                    </div>
                </div>
            </div>
        </div>
</div>


{% endblock %}