personal_blog/blueprints/admin.py
from flask import Blueprint, render_template, url_for, redirect, flash, request, send_from_directory
from personal_blog.models import Admin, Post, Category
from flask_login import login_user, logout_user, login_required, current_user
from personal_blog.form import LoginForm, RegisterForm, PostForm, AdminForm, SetPasswordform, CategoryForm
from personal_blog.setting import redirect_back
from personal_blog.extensions import db
import personal_blog.tools as tools
from flask_ckeditor import CKEditor, CKEditorField, upload_fail, upload_success
# import personal_blog.config as config
import os
admin_bp = Blueprint('admin', __name__)


@admin_bp.route('/register', methods=['GET', 'POST'])
def register():
    form = RegisterForm()
    print(request.remote_addr)
    if form.validate_on_submit():
        username = form.username.data
        password = form.password.data
        # remember = form.remember.data

        admin = Admin(
            username=username,
        )
        # print(password)
        admin.set_password(password)

        db.session.add(admin)
        db.session.commit()
        flash('注册成功', 'info')
        return redirect(url_for('admin.login'))
        # admin = Admin.query.first()
        # if admin:
        # if admin.check_password(password):
        # login_user(admin, remember)
        #

    return render_template('admin/register.html', form=form)

@admin_bp.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        flash(u'你已经登录了！', 'info')
        return redirect(url_for('blog.index'))

    form = LoginForm()
    if form.validate_on_submit():
        username = form.username.data
        password = form.password.data
        remember = form.remember.data

        admin = Admin.query.filter_by(username=username).first()
        print('user',admin.id)
        # config.get_id = admin.id
        # config._init()
        with open('personal_blog/config','w') as f:
            f.write(str(admin.id))
        # config.set_value(admin.id)
        # print(config.get_value())
        if admin:
            if admin.check_password(password):
                login_user(admin, remember)
                # config.user_id =admin.get_id()
                # print(config.user_id)
                flash('登录成功', 'info')
                tools.add_log(request.remote_addr,'登录')
                return redirect_back()

            flash('账号密码错误', 'warning')
        else:
            flash('No account.', 'warning')
    return render_template('admin/login.html', form=form)


@admin_bp.route('/logout')
@login_required
def logout():
    logout_user()
    flash(u'退出登录', 'info')
    return redirect_back()


@admin_bp.route('/setting')
@login_required  # 视图保护，只有登录了才能看到这个被这个装饰器修饰的路由
def setting():
    return render_template('admin/setting.html')


@admin_bp.route('/category/manage')
@login_required
def manage_category():
    categories = Category.query.all()
    return render_template('admin/manage_category.html', categories=categories)


@admin_bp.route('/category/new', methods=['GET', 'POST'])
@login_required
def new_category():
    form = CategoryForm()
    if form.validate_on_submit():
        name = form.name.data
        category = Category(name=name)
        db.session.add(category)
        db.session.commit()
        flash('分类创建成功！', 'success')
        tools.add_log(request.remote_addr, '新建分类')
        return redirect(url_for('.manage_category'))
    return render_template('admin/new_category.html', form=form)


@admin_bp.route('/category/<int:category_id>/edit', methods=['GET', 'POST'])
@login_required
def edit_category(category_id):
    form = CategoryForm()
    category = Category.query.get_or_404(category_id)
    if category.id == 1:
        flash('你不能修改默认的分类', 'warning')
        return redirect('blog.index')
    if form.validate_on_submit():
        category.name = form.name.data
        db.session.commit()
        flash('文章分类更新成功')
        tools.add_log(request.remote_addr, '编辑分类')
        return redirect(url_for('.manage_category'))
    form.name.data = category.name
    return render_template('/admin/edit_category.html', form=form)


@admin_bp.route('/category<int:category_id>/delete', methods=['POST'])
@login_required
def delete_category(category_id):
    category = Category.query.get_or_404(category_id)
    if category.id == 1:
        flash('你不能删除默认的分类', 'warning')
        return redirect('blog.index')
    category.delete()
    flash('分类删除成功')
    tools.add_log(request.remote_addr, '删除分类')
    return redirect(url_for('.manage_category'))


@admin_bp.route('/manage_post')  # 文章管理
@login_required
def manage():
    with open('personal_blog/config', 'r') as f:
        s = f.read()
    id = int(s)
    print(id)
    page = request.args.get('page', 1, type=int)  # 从查询字符串中获取当前页数
    per_page = 5  # 每页的数量
    pagination = Post.query.filter_by(user_id=id).order_by(Post.timestamp.desc()).paginate(page, per_page=per_page)  # 分页对象
    posts = pagination.items  # 当前页数记录的列表

    return render_template('admin/manage_post.html', pagination=pagination, posts=posts)


@admin_bp.route('/post/<int:post_id>/edit', methods=['GET', 'POST'])
@login_required
def edit_post(post_id):
    form = PostForm()
    post = Post.query.get_or_404(post_id)
    if form.validate_on_submit():
        post.title = form.title.data
        post.category = Category.query.get(form.category.data)
        post.body = form.body.data
        db.session.commit()
        flash('文章更新成功')
        tools.add_log(request.remote_addr, '编辑文章')
        return redirect(url_for('blog.show_post', post_id=post.id))
    form.title.data = post.title
    form.category.data = post.category_id
    form.body.data = post.body
    return render_template('/admin/edit_post.html', form=form)


@admin_bp.route('/post/<int:post_id>/delete', methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    db.session.delete(post)
    db.session.commit()
    tools.add_log(request.remote_addr, '删除文章')
    flash('文章删除成功！')
    return redirect_back()


@admin_bp.route('/new_post', methods=['POST', 'GET'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        title = form.title.data
        body = form.body.data
        category = Category.query.get(form.category.data)
        with open('personal_blog/config', 'r') as f:
            s = f.read()
        id = int(s)
        print(id)
        admin = Admin.query.get(id)
        post = Post(title=title, category=category, body=body,admin=admin)
        db.session.add(post)
        db.session.commit()
        tools.add_log(request.remote_addr, '新建文章')
        flash('博客发表成功')
        return redirect(url_for('blog.index'))
    return render_template('/admin/new_post.html', form=form)


# 修改关于
@admin_bp.route('/edit_individual_resume', methods=['GET', 'POST'])
def edit_indicidual_resume():
    cate = Category.query.filter_by(name='individual_resume').first()
    post = Post.query.filter_by(category=cate).first()
    return redirect(url_for('admin.edit_post', post_id=post.id))


# 修改网站介绍
@admin_bp.route('/edit_this_site', methods=['GET', 'POST'])
def edit_this_site():
    cate = Category.query.filter_by(name='this_site').first()
    post = Post.query.filter_by(category=cate).first()
    return redirect(url_for('admin.edit_post', post_id=post.id))


@admin_bp.route('/set_password', methods=['GET', 'POST'])
@login_required
def set_password():
    form = SetPasswordform()
    if form.validate_on_submit():
        username = form.username.data
        print(username)
        admin = Admin.query.filter_by(username=username).first()
        # admin = Admin.query.first()
        new_password = form.password.data
        admin.username = form.username.data
        admin.set_password(new_password)
        db.session.add(admin)
        db.session.commit()
        flash('密码修改成功')
        return redirect(url_for('blog.index'))
    return render_template('/admin/set_password.html', form=form)


@admin_bp.route('/files/<path:filename>')
def uploaded_files(filename):
    path = '/the/uploaded/directory'
    return send_from_directory(path, filename)


@admin_bp.route('/upload', methods=['POST'])
@login_required
def upload():
    f = request.files.get('upload')  # 获取上传图片文件对象, 键必须为'upload'
    extensions = f.filename.split('.')[-1].lower()
    if extensions not in ['png', 'jpg', 'gif', 'jpeg']:
        return uploaded_fail(message='只能上传图片')
    f.save(os.path.join(app.config['UPLOAED'], f.filename))
    url = url_for('uploads_files', filename=f.filename)
    return upload_success(url=url)

personal_blog/blueprints/blog.py
from flask import Blueprint, render_template, request, flash, current_app
from personal_blog.models import Post, Category,Admin,Log

from personal_blog.form import LoginForm, RegisterForm, PostForm, AdminForm, SetPasswordform, CategoryForm,SearchForm
# import personal_blog.config as config
import os
blog_bp = Blueprint('blog', __name__)


# .filter(Post.category.name != 'this_site', Post.category.name != 'individual_resume')
@blog_bp.route('/')
def index():
    page = request.args.get('page', 1, type=int)  # 从查询字符串中获取当前页数
    cate1 = Category.query.filter_by(name='网站介绍').first()    # 网站介绍的分类。
    cate2 = Category.query.filter_by(name='个人介绍').first()  # 关于的分类。
    cate3 = Category.query.filter_by(name='生活').first()           # 文字的分类，起的名称是life。
    per_page = 8    # 每页的数量
    pagination = Post.query.filter(Post.category != cate1, Post.category != cate2, Post.category != cate3).order_by(Post.timestamp.desc()).paginate(page, per_page=per_page) # 分页对象
    posts = pagination.items    # 当前页数记录的列表
    return render_template('blog/index.html', pagination=pagination, posts=posts)


@blog_bp.route('/life')
def index_life():
    page = request.args.get('page', 1, type=int)  # 从查询字符串中获取当前页数
    cate = Category.query.filter_by(name='生活').first()
    per_page = 8  # 每页的数量
    pagination = Post.query.filter(Post.category == cate).order_by(Post.timestamp.desc()).paginate(page, per_page=per_page)  # 分页对象
    posts = pagination.items  # 当前页数记录的列表
    return render_template('blog/index.html', pagination=pagination, posts=posts)


@blog_bp.route('/post/<int:post_id>', methods=['GET', 'POST'])
def show_post(post_id):
    post = Post.query.filter().get_or_404(post_id)
    page = request.args.get('page', 1, type=int)
    per_page = 8
    pagination = Post.query.order_by(Post.timestamp.desc()).paginate(page, per_page=per_page)

    return render_template('blog/post.html', post=post, pagination=pagination)


@blog_bp.route('/category/<int:category_id>')
def show_category(category_id):
    category = Category.query.get_or_404(category_id)
    page = request.args.get('page', 1, type=int)
    per_page = 5
    pagination = Post.query.with_parent(category).order_by(Post.timestamp.desc()).paginate(page, per_page)
    posts = pagination.items
    return render_template('blog/category.html', category=category, pagination=pagination, posts=posts)


@blog_bp.route('/my_blog')
def show_my_blog():
    with open('personal_blog/config', 'r') as f:
        s = f.read()
    id = int(s)
    print(id)
    admin = Admin.query.get_or_404(id)
    page = request.args.get('page', 1, type=int)
    per_page = 5
    pagination = Post.query.with_parent(admin).order_by(Post.timestamp.desc()).paginate(page, per_page)
    posts = pagination.items
    return render_template('blog/my_blog.html', admin=admin, pagination=pagination, posts=posts)

@blog_bp.route('/log')
def log():
    logs = Log.query.all()
    for i in logs:
        print(i.ip)
    return render_template('blog/log.html', logs= logs)


@blog_bp.route('/search',methods=['GET', 'POST'])
def search():
    # print('ss')
    form = SearchForm()
    if form.validate_on_submit():
        search= form.search.data
        page = request.args.get('page', 1, type=int)
        per_page = 5
        pagination = Post.query.filter(Post.title.like('%'+search+'%')).order_by(Post.timestamp.desc()).paginate(page, per_page)
        posts = pagination.items
        return render_template('blog/show_search.html',  pagination=pagination, posts=posts)
    # category = Category.query.get_or_404(category_id)

    return render_template('blog/search.html', form=form)


@blog_bp.route('/individual_resume')
def individual_resume():
    cate = Category.query.filter_by(name='个人介绍').first()
    post = Post.query.filter_by(category=cate).first()
    return render_template('blog/individual_resume.html', post=post)


@blog_bp.route('/this_site')
def this_site():
    cate = Category.query.filter_by(name='网站介绍').first()
    post = Post.query.filter_by(category=cate).first()
    return render_template('blog/this_site.html', post=post)

personal_blog/templates/base.html
<!DOCTYPE html>
<html lang="zh-CN">

<head>
    {% block head %}
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>{% block title %}{% endblock title %}</title>
        {% block daima %} {% endblock daima %}

        <link href="{{ url_for('static', filename = 'css/bootstrap.min.css') }}" rel="stylesheet"/>
        <link href="{{ url_for('static', filename = 'css/x.css') }}" rel="stylesheet">
        <link href="{{ url_for('static', filename = 'css/style.css') }}" rel="stylesheet">
        <link rel="stylesheet" href="https://cdn.bootcss.com/normalize/8.0.1/normalize.min.css">
    {% endblock %}
</head>

<body class="backgroud1">

<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{{ url_for('blog.index') }}">
                首页
            </a>
            {#                    <h3>PLX#}
            {#                    </h3>#}
            {#                <br>#}
            {#                    <h2>#}
            {#                        BLOG#}
            {#                    </h2>#}
            {#                    <img src="{{ url_for('static', filename='pics/logo.jpg') }}" alt=""> </a>#}
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li>
                    <a href="{{ url_for('blog.show_my_blog') }}">我的博客</a>
                </li>
                <li>
                    <a class="nav-link" href="{{ url_for('admin.new_post') }}">发表新博客</a>
                </li>
                <li>
                    <a class="nav-link" href="{{ url_for('blog.search') }}">搜索</a>
                </li>
                   <li>
                    <a class="nav-link" href="{{ url_for('blog.log') }}">日志</a>
                </li>
                <li>
                    {% if current_user.is_authenticated %}
                        <a href="{{ url_for('admin.setting') }}">设置</a>
                    {% endif %}
                </li>
                <li>
                    <a href="https://gitee.com/Yuandaorrr/" target="_blank">我的gitee</a>
                </li>

            </ul>

            {#            <form action="/show_search" method="POST" class="navbar-form navbar-left">#}
            {#                <div class="form-group">#}
            {#                    <input type="text"  name="username" class="form-control" placeholder="输入搜索关键字">#}
            {#                </div>#}
            {#                <button type="submit" class="btn btn-default">搜索</button>#}
            {# <a href="{{ url_for('.show_category', category_id=post.category.id) }}" style="color:#6699FF">{{ post.category.name }}</a>#}
            {#            </form>#}
            {#            <form>#}
            {#                <legend>Please sign in:</legend>#}
            {#                <input type="text" name="username"/>#}
            {#                <br/>#}
            {#                <input type="password" name="password"/>#}
            {#                <br/>#}
            {#                <button type="submit">提交</button>#}
            {#            </form>#}

            <ul class="nav navbar-nav navbar-right">

                <li><a class="btn" href={{ url_for('admin.login') }}>登录</a></li>

                <li><a class="btn" href={{ url_for('admin.register') }}>注册</a>
                </li>
            </ul>

        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>
<div class="container">


    {#    <div class="row">#}
    {#        <div class="col-md-3">#}
    {#            <div class="myself">#}
    {#                <a>#}
    {##}
    {##}
    {#                </a>#}
    {#            </div>#}
    {#        </div>#}
    {##}
    {#        <div class="col-md-4">#}
    {#            <input id="q" type="text" placeholder="输入搜索关键字">#}
    {#        </div>#}
    {##}
    {#        <div class="col-md-1">#}
    {#            <button id="s"#}
    {#                    class="btn u-btn-white g-color-primary--hover g-bg-secondary g-font-weight-600 g-font-size-13 text-uppercase rounded g-py-12 g-px-20"#}
    {#                    type="submit">#}
    {#                <span class="g-hidden-md-down">搜索</span>#}
    {#                <i class="g-hidden-lg-up fa fa-search"></i>#}
    {#            </button>#}
    {#        </div>#}
    {##}
    {#        <div class="col-md-1">#}
    {##}
    {#        </div>#}
    {#        <div class="col-md-1">#}
    {##}
    {#        </div>#}
    {##}
    {#        <div class="col-md-1">#}
    {##}
    {#        </div>#}
    {#    </div>#}


    {#    {% block navbar %}#}
    {##}
    {#        <ul class="nav nav-pills navbar-fixed-top" style="margin-top:60px">#}
    {#            <li class="nav-item">#}
    {#                <a class="nav-link" href="{{ url_for('blog.index') }}">首页</a>#}
    {#            </li>#}
    {#            <li class="nav-item">#}
    {##}
    {#            </li>#}
    {#            <li class="nav-item">#}
    {##}
    {#            </li>#}
    {#            <li class="nav-item">#}
    {##}
    {#            </li>#}
    {#            <li class="nav-item">#}
    {##}
    {#            </li>#}
    {#        </ul>#}
    {#    {% endblock %}#}


    <div class="row">
        <br>
    </div>


    {#    <div class="main">#}
    {#        {% for message in get_flashed_messages(with_categories=True) %}#}
    {#            <div class="alert alert-{{ message[0] }}" role="alert">#}
    {#                <button type="button" class="close" data-dismiss="alert">&times</button>#}
    {#                {{ message[1] }}#}
    {#            </div>#}
    {#        {% endfor %}#}
    {##}
    {#    </div>#}

    <div class="row">
        <div>
            {% block content %}
            {% endblock content %}

            {% block footer %}
            {% endblock %}

        </div>

        {#        {% block subhead %}#}
        {#        {% endblock subhead %}#}

        {% block scripts %}
            <script type="text/javascript"
                    src="{{ url_for('static', filename='js/jquery-3.2.1.slim.min.js') }}"></script>
            <script type="text/javascript" src="{{ url_for('static', filename='js/popper.min.js') }}"></script>
            <script type="text/javascript" src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
            <script type="text/javascript" src="{{ url_for('static', filename='js/script.js') }}"></script>
            <!-- <script type="text/javascript" src="https://cdn.bootcss.com/canvas-nest.js/1.0.1/canvas-nest.min.js"></script> -->
            {{ moment.include_moment(local_js=url_for('static', filename='js/moment-with-locales.min.js')) }}
            {{ moment.locale('zh-cn') }}
        {% endblock %}
    </div>


</div>

</body>

</html>

personal_blog/templates/base_edit.html
{% extends 'post_detail.html' %}
{% from 'bootstrap/form.html' import render_form %}


{% block head %}
    {{ super() }}
    <script type="text/javascript" src="{{ url_for('static', filename='ckeditor/ckeditor.js') }}"></script>

{% endblock %}


{% block title %} 编辑文章 {% endblock %}
{% block content %}
    <form method="POST">

        {{ form.csrf_token }}

        {{ form.title.label }}
        <br>
        {{ form.title }}
        <br><br>
        {{ form.category.label }}
        <br>
        {{ form.category }}
        <br><br>
        {{ form.body.label }}
        <br><br>
        {{ form.body }}
        <br><br>

        {{ form.submit }}
    </form>
    <br>
    <br>
    <br>
    <br>
{% endblock %}
    

personal_blog/templates/base_edit2.html
{% extends 'post_detail.html' %}
{% from 'bootstrap/form.html' import render_form %}


{% block head %}
    {{ super() }}
    <script type="text/javascript" src="{{ url_for('static', filename='ckeditor/ckeditor.js') }}"></script>

{% endblock %}


{% block title %} 编辑分类 {% endblock %}
{% block content %}
    <form method="POST">

        {{ form.csrf_token }}

        {{ form.name }}

        <br><br>

        {{ form.submit }}
    </form>
    <br>
    <br>
    <br>
    <br>
{% endblock %}
    

personal_blog/templates/post_detail.html
{% extends 'base.html' %}

{% block subhead %}
<h1>文章目录</h1>
            <div id="subtitle">
                <ul>

                </ul>
            </div>
{% endblock %}

{% block scripts %}
    {{ super() }}

    {{ ckeditor.config(name='body') }}
    <script type="text/javascript" src="{{ url_for('static', filename='js/post_script.js') }}"></script>
{% endblock %}